server:
  port: 8080
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
  application:
    name: integration-spring-ai
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-ai-demo
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect

  ai:
    openai:
      api-key: ${GEMINI_KEY}
      chat:
        base-url: https://generativelanguage.googleapis.com
        completions-path: /v1beta/openai/chat/completions
        options:
          model: gemini-2.5-flash
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always